#!/usr/bin/env python3
"""Add picker cities for catalog countries that have no citiesByCountry entry."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSET_PATH = ROOT / "app/src/main/assets/locations.json"
TEST_RESOURCE_PATH = ROOT / "app/src/test/resources/locations.json"

# Capital + major cities (~10 per country). Jun 2026 — Americas, Caribbean, Pacific, KR/TW/BT.
REMAINING_EXPANSION: dict[str, list[str]] = {
    "BB": [
        "Bridgetown",
        "Speightstown",
        "Oistins",
        "Holetown",
        "Bathsheba",
        "Crane",
        "Six Cross Roads",
        "Warrens",
        "Black Rock",
        "Hastings",
    ],
    "BO": [
        "La Paz",
        "Santa Cruz",
        "Cochabamba",
        "Sucre",
        "Oruro",
        "Tarija",
        "Potosi",
        "Trinidad",
        "Cobija",
        "Yacuiba",
    ],
    "BS": [
        "Nassau",
        "Freeport",
        "West End",
        "Marsh Harbour",
        "Coopers Town",
        "High Rock",
        "Clarence Town",
        "Dunmore Town",
        "Alice Town",
        "George Town",
    ],
    "BT": [
        "Thimphu",
        "Phuntsholing",
        "Punakha",
        "Gelephu",
        "Paro",
        "Trashigang",
        "Mongar",
        "Jakar",
        "Samdrup Jongkhar",
        "Wangdue Phodrang",
    ],
    "BZ": [
        "Belize City",
        "Belmopan",
        "San Ignacio",
        "Orange Walk",
        "Dangriga",
        "Corozal",
        "San Pedro",
        "Punta Gorda",
        "Benque Viejo del Carmen",
        "Placencia",
    ],
    "CR": [
        "San Jose",
        "Alajuela",
        "Cartago",
        "Heredia",
        "Limon",
        "Puntarenas",
        "Liberia",
        "San Isidro",
        "Quesada",
        "Curridabat",
    ],
    "CU": [
        "Havana",
        "Santiago de Cuba",
        "Camaguey",
        "Holguin",
        "Guantanamo",
        "Santa Clara",
        "Bayamo",
        "Cienfuegos",
        "Pinar del Rio",
        "Matanzas",
    ],
    "DM": [
        "Roseau",
        "Portsmouth",
        "Marigot",
        "Berekua",
        "Mahaut",
        "Saint Joseph",
        "Wesley",
        "Salisbury",
        "La Plaine",
        "Castle Bruce",
    ],
    "DO": [
        "Santo Domingo",
        "Santiago de los Caballeros",
        "La Romana",
        "San Pedro de Macoris",
        "San Francisco de Macoris",
        "Puerto Plata",
        "La Vega",
        "Barahona",
        "San Cristobal",
        "Higuey",
    ],
    "EC": [
        "Guayaquil",
        "Quito",
        "Cuenca",
        "Santo Domingo",
        "Machala",
        "Duran",
        "Manta",
        "Portoviejo",
        "Loja",
        "Ambato",
    ],
    "FJ": [
        "Suva",
        "Lautoka",
        "Nadi",
        "Labasa",
        "Ba",
        "Levuka",
        "Sigatoka",
        "Rakiraki",
        "Nausori",
        "Savusavu",
    ],
    "FM": [
        "Palikir",
        "Weno",
        "Kolonia",
        "Tofol",
        "Colonia",
        "Lelu",
        "Nema",
        "Satowan",
        "Lukunor",
        "Kuttu",
    ],
    "GD": [
        "St. George's",
        "Gouyave",
        "Grenville",
        "Victoria",
        "Sauteurs",
        "Hillsborough",
        "Woburn",
        "Grand Roy",
        "Concord",
        "Tivoli",
    ],
    "GT": [
        "Guatemala City",
        "Mixco",
        "Villa Nueva",
        "Quetzaltenango",
        "Escuintla",
        "San Juan Sacatepequez",
        "Villa Canales",
        "Petapa",
        "Chinautla",
        "Huehuetenango",
    ],
    "GY": [
        "Georgetown",
        "Linden",
        "New Amsterdam",
        "Anna Regina",
        "Bartica",
        "Skeldon",
        "Rosignol",
        "Mahaica",
        "Fort Wellington",
        "Lethem",
    ],
    "HN": [
        "Tegucigalpa",
        "San Pedro Sula",
        "Choloma",
        "La Ceiba",
        "El Progreso",
        "Choluteca",
        "Comayagua",
        "Puerto Cortes",
        "La Lima",
        "Danli",
    ],
    "HT": [
        "Port-au-Prince",
        "Carrefour",
        "Delmas",
        "Petion-Ville",
        "Gonaives",
        "Cap-Haitien",
        "Les Cayes",
        "Jacmel",
        "Saint-Marc",
        "Verrettes",
    ],
    "JM": [
        "Kingston",
        "Montego Bay",
        "Spanish Town",
        "Portmore",
        "Mandeville",
        "May Pen",
        "Old Harbour",
        "Linstead",
        "Half Way Tree",
        "Savanna-la-Mar",
    ],
    "KI": [
        "Tarawa",
        "Betio",
        "Bairiki",
        "Bikenibeu",
        "Teaoraereke",
        "Ambo",
        "Banraeaba",
        "Taburao",
        "Tabuki",
        "Roreti",
    ],
    "KR": [
        "Seoul",
        "Busan",
        "Incheon",
        "Daegu",
        "Daejeon",
        "Gwangju",
        "Suwon",
        "Ulsan",
        "Changwon",
        "Seongnam",
    ],
    "LC": [
        "Castries",
        "Bisee",
        "Vieux Fort",
        "Micoud",
        "Soufriere",
        "Dennery",
        "Gros Islet",
        "Anse La Raye",
        "Canaries",
        "Laborie",
    ],
    "MH": [
        "Majuro",
        "Ebeye",
        "Laura",
        "Rairok",
        "Ajeltake",
        "Rita",
        "Wotje",
        "Jaluit",
        "Kwajalein",
        "Arno",
    ],
    "MX": [
        "Mexico City",
        "Guadalajara",
        "Monterrey",
        "Puebla",
        "Tijuana",
        "Leon",
        "Ciudad Juarez",
        "Zapopan",
        "Merida",
        "San Luis Potosi",
    ],
    "NI": [
        "Managua",
        "Leon",
        "Masaya",
        "Chinandega",
        "Matagalpa",
        "Esteli",
        "Granada",
        "Jinotepe",
        "Bluefields",
        "Rivas",
    ],
    "NR": [
        "Yaren",
        "Aiwo",
        "Anabar",
        "Anetan",
        "Anibare",
        "Baiti",
        "Boe",
        "Buada",
        "Denigomodu",
        "Meneng",
    ],
    "PA": [
        "Panama City",
        "San Miguelito",
        "David",
        "Colon",
        "La Chorrera",
        "Penonome",
        "Chitre",
        "Santiago",
        "Aguadulce",
        "Arraijan",
    ],
    "PG": [
        "Port Moresby",
        "Lae",
        "Mount Hagen",
        "Madang",
        "Goroka",
        "Kokopo",
        "Mendi",
        "Kimbe",
        "Bulolo",
        "Wewak",
    ],
    "PY": [
        "Asuncion",
        "Ciudad del Este",
        "San Lorenzo",
        "Luque",
        "Capiata",
        "Lambare",
        "Fernando de la Mora",
        "Limpio",
        "Nemby",
        "Encarnacion",
    ],
    "SM": [
        "San Marino",
        "Serravalle",
        "Borgo Maggiore",
        "Domagnano",
        "Fiorentino",
        "Acquaviva",
        "Faetano",
        "Chiesanuova",
        "Montegiardino",
        "Dogana",
    ],
    "SR": [
        "Paramaribo",
        "Lelydorp",
        "Nieuw Nickerie",
        "Moengo",
        "Nieuw Amsterdam",
        "Marienburg",
        "Wageningen",
        "Albina",
        "Groningen",
        "Brokopondo",
    ],
    "SV": [
        "San Salvador",
        "Santa Ana",
        "San Miguel",
        "Mejicanos",
        "Soyapango",
        "Santa Tecla",
        "Apopa",
        "Delgado",
        "Ahuachapan",
        "Ilopango",
    ],
    "TL": [
        "Dili",
        "Baucau",
        "Maliana",
        "Suai",
        "Liquica",
        "Ermera",
        "Aileu",
        "Manatuto",
        "Viqueque",
        "Same",
    ],
    "TO": [
        "Nuku'alofa",
        "Neiafu",
        "Haveluloto",
        "Vaini",
        "Pangai",
        "Ohonua",
        "Mu'a",
        "Ha'ateiho",
        "Kolonga",
        "Nukunuku",
    ],
    "TT": [
        "Port of Spain",
        "San Fernando",
        "Chaguanas",
        "Arima",
        "Point Fortin",
        "Tunapuna",
        "Scarborough",
        "Princes Town",
        "Diego Martin",
        "Siparia",
    ],
    "TV": [
        "Funafuti",
        "Vaiaku",
        "Savave",
        "Tanrake",
        "Asau",
        "Lolua",
        "Tonga",
        "Niulakita",
        "Motufoua",
        "Fagatua",
    ],
    "TW": [
        "Taipei",
        "Kaohsiung",
        "Taichung",
        "Tainan",
        "Hsinchu",
        "Keelung",
        "Chiayi",
        "Changhua",
        "Pingtung",
        "Taoyuan",
    ],
    "VU": [
        "Port Vila",
        "Luganville",
        "Norsup",
        "Isangel",
        "Lakatoro",
        "Sola",
        "Longana",
        "Port Olry",
        "Saratamata",
        "Lenakel",
    ],
    "WS": [
        "Apia",
        "Vaitele",
        "Faleula",
        "Siusega",
        "Malie",
        "Afega",
        "Leulumoega",
        "Fasitoouta",
        "Vailoa",
        "Safotu",
    ],
}


def main() -> int:
    data = json.loads(ASSET_PATH.read_text(encoding="utf-8"))
    cities = data.setdefault("citiesByCountry", {})
    added = 0
    skipped = 0
    for code, city_list in sorted(REMAINING_EXPANSION.items()):
        existing = cities.get(code, [])
        if existing:
            print(f"SKIP {code}: already has {len(existing)} cities")
            skipped += 1
            continue
        cities[code] = city_list
        added += len(city_list)
        print(f"ADD {code}: {len(city_list)} cities")

    output = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    ASSET_PATH.write_text(output, encoding="utf-8")
    TEST_RESOURCE_PATH.write_text(output, encoding="utf-8")
    print(f"\nAdded {added} cities across {len(REMAINING_EXPANSION) - skipped} countries")
    print(f"File size: {len(output.encode('utf-8'))} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
