#!/usr/bin/env python3
"""Add picker cities for African countries that exist in catalog but have no citiesByCountry entry."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSET_PATH = ROOT / "app/src/main/assets/locations.json"
TEST_RESOURCE_PATH = ROOT / "app/src/test/resources/locations.json"

# Capital + major cities (~10 per country). Keys must match countries[].code in locations.json.
AFRICA_EXPANSION: dict[str, list[str]] = {
    "AO": [
        "Luanda",
        "Huambo",
        "Lobito",
        "Benguela",
        "Lubango",
        "Namibe",
        "Malanje",
        "Soyo",
        "Cabinda",
        "Uige",
    ],
    "BF": [
        "Ouagadougou",
        "Bobo-Dioulasso",
        "Koudougou",
        "Banfora",
        "Ouahigouya",
        "Pouytenga",
        "Fada N'Gourma",
        "Dedougou",
        "Tenkodogo",
        "Hounde",
    ],
    "BI": [
        "Bujumbura",
        "Gitega",
        "Ngozi",
        "Rumonge",
        "Muyinga",
        "Ruyigi",
        "Kayanza",
        "Bururi",
        "Makamba",
        "Bubanza",
    ],
    "BJ": [
        "Cotonou",
        "Porto-Novo",
        "Parakou",
        "Djougou",
        "Bohicon",
        "Abomey-Calavi",
        "Natitingou",
        "Lokossa",
        "Ouidah",
        "Abomey",
    ],
    "BW": [
        "Gaborone",
        "Francistown",
        "Maun",
        "Serowe",
        "Kanye",
        "Mahalapye",
        "Molepolole",
        "Mogoditshane",
        "Lobatse",
        "Selibe Phikwe",
    ],
    "CD": [
        "Kinshasa",
        "Lubumbashi",
        "Mbuji-Mayi",
        "Kisangani",
        "Kananga",
        "Goma",
        "Bukavu",
        "Kolwezi",
        "Tshikapa",
        "Matadi",
    ],
    "CF": [
        "Bangui",
        "Bimbo",
        "Berberati",
        "Carnot",
        "Bambari",
        "Bouar",
        "Bossangoa",
        "Bria",
        "Bangassou",
        "Nola",
    ],
    "CG": [
        "Brazzaville",
        "Pointe-Noire",
        "Dolisie",
        "Nkayi",
        "Owando",
        "Ouesso",
        "Loandjili",
        "Madingou",
        "Gamboma",
        "Impfondo",
    ],
    "CI": [
        "Abidjan",
        "Bouake",
        "Daloa",
        "Yamoussoukro",
        "San-Pedro",
        "Korhogo",
        "Man",
        "Divo",
        "Gagnoa",
        "Anyama",
    ],
    "CM": [
        "Douala",
        "Yaounde",
        "Garoua",
        "Bamenda",
        "Maroua",
        "Bafoussam",
        "Ngaoundere",
        "Bertoua",
        "Kumba",
        "Limbe",
    ],
    "CV": [
        "Praia",
        "Mindelo",
        "Santa Maria",
        "Espargos",
        "Assomada",
        "Porto Novo",
        "Sao Filipe",
        "Tarrafal",
        "Ribeira Grande",
        "Sal Rei",
    ],
    "ER": [
        "Asmara",
        "Keren",
        "Massawa",
        "Assab",
        "Mendefera",
        "Barentu",
        "Adi Keyh",
        "Dekemhare",
        "Akordat",
        "Senafe",
    ],
    "GA": [
        "Libreville",
        "Port-Gentil",
        "Franceville",
        "Oyem",
        "Moanda",
        "Mouila",
        "Lambarene",
        "Tchibanga",
        "Koulamoutou",
        "Makokou",
    ],
    "GM": [
        "Banjul",
        "Serekunda",
        "Brikama",
        "Bakau",
        "Farafenni",
        "Lamin",
        "Sukuta",
        "Brufut",
        "Gunjur",
        "Basse Santa Su",
    ],
    "GN": [
        "Conakry",
        "Nzerekore",
        "Kankan",
        "Kindia",
        "Labe",
        "Mamou",
        "Boke",
        "Siguiri",
        "Gueckedou",
        "Dalaba",
    ],
    "GQ": [
        "Malabo",
        "Bata",
        "Ebebiyin",
        "Aconibe",
        "Anisoc",
        "Luba",
        "Evinayong",
        "Mongomo",
        "Ebolowa",
        "Mbini",
    ],
    "GW": [
        "Bissau",
        "Bafata",
        "Gabu",
        "Bissora",
        "Bolama",
        "Cacheu",
        "Catio",
        "Mansoa",
        "Bubaque",
        "Farim",
    ],
    "LR": [
        "Monrovia",
        "Gbarnga",
        "Buchanan",
        "Ganta",
        "Kakata",
        "Bensonville",
        "Harper",
        "Voinjama",
        "Zwedru",
        "Pleebo",
    ],
    "LS": [
        "Maseru",
        "Teyateyaneng",
        "Mafeteng",
        "Hlotse",
        "Mohale's Hoek",
        "Quthing",
        "Qacha's Nek",
        "Butha-Buthe",
        "Mokhotlong",
        "Thaba-Tseka",
    ],
    "MG": [
        "Antananarivo",
        "Toamasina",
        "Antsirabe",
        "Mahajanga",
        "Fianarantsoa",
        "Toliara",
        "Antsiranana",
        "Ambovombe",
        "Ambanja",
        "Moramanga",
    ],
    "ML": [
        "Bamako",
        "Sikasso",
        "Mopti",
        "Koutiala",
        "Segou",
        "Gao",
        "Kayes",
        "Kati",
        "Markala",
        "Koulikoro",
    ],
    "MW": [
        "Lilongwe",
        "Blantyre",
        "Mzuzu",
        "Zomba",
        "Karonga",
        "Kasungu",
        "Mangochi",
        "Salima",
        "Nkhotakota",
        "Rumphi",
    ],
    "MZ": [
        "Maputo",
        "Matola",
        "Nampula",
        "Beira",
        "Chimoio",
        "Nacala",
        "Quelimane",
        "Tete",
        "Xai-Xai",
        "Pemba",
    ],
    "NA": [
        "Windhoek",
        "Rundu",
        "Walvis Bay",
        "Oshakati",
        "Swakopmund",
        "Katima Mulilo",
        "Grootfontein",
        "Rehoboth",
        "Otjiwarongo",
        "Okahandja",
    ],
    "NE": [
        "Niamey",
        "Zinder",
        "Maradi",
        "Agadez",
        "Tahoua",
        "Dosso",
        "Diffa",
        "Birni N'Konni",
        "Tessaoua",
        "Arlit",
    ],
    "RW": [
        "Kigali",
        "Huye",
        "Muhanga",
        "Musanze",
        "Rubavu",
        "Byumba",
        "Rusizi",
        "Karongi",
        "Rwamagana",
        "Nyanza",
    ],
    "SC": [
        "Victoria",
        "Anse Boileau",
        "Beau Vallon",
        "Takamaka",
        "Port Glaud",
        "Baie Lazare",
        "Grand Anse",
        "Cascade",
        "Bel Ombre",
        "Anse Royale",
    ],
    "SZ": [
        "Mbabane",
        "Manzini",
        "Big Bend",
        "Malkerns",
        "Nhlangano",
        "Siteki",
        "Matsapha",
        "Piggs Peak",
        "Lobamba",
        "Mhlume",
    ],
    "TD": [
        "N'Djamena",
        "Moundou",
        "Abeche",
        "Sarh",
        "Kelo",
        "Koumra",
        "Pala",
        "Am Timan",
        "Bongor",
        "Mongo",
    ],
    "TG": [
        "Lome",
        "Sokode",
        "Kara",
        "Kpalime",
        "Atakpame",
        "Dapaong",
        "Tsevie",
        "Aneho",
        "Bassar",
        "Mango",
    ],
    "UG": [
        "Kampala",
        "Gulu",
        "Lira",
        "Mbarara",
        "Jinja",
        "Mbale",
        "Masaka",
        "Entebbe",
        "Fort Portal",
        "Arua",
    ],
    "ZM": [
        "Lusaka",
        "Kitwe",
        "Ndola",
        "Kabwe",
        "Chingola",
        "Mufulira",
        "Livingstone",
        "Luanshya",
        "Chipata",
        "Kasama",
    ],
    "ZW": [
        "Harare",
        "Bulawayo",
        "Chitungwiza",
        "Mutare",
        "Gweru",
        "Kwekwe",
        "Masvingo",
        "Kadoma",
        "Marondera",
        "Victoria Falls",
    ],
}


def main() -> int:
    data = json.loads(ASSET_PATH.read_text(encoding="utf-8"))
    cities = data.setdefault("citiesByCountry", {})
    added = 0
    for code, city_list in sorted(AFRICA_EXPANSION.items()):
        existing = cities.get(code, [])
        if existing:
            print(f"SKIP {code}: already has {len(existing)} cities")
            continue
        cities[code] = city_list
        added += len(city_list)
        print(f"ADD {code}: {len(city_list)} cities")

    output = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    ASSET_PATH.write_text(output, encoding="utf-8")
    TEST_RESOURCE_PATH.write_text(output, encoding="utf-8")
    print(f"\nAdded {added} cities across {len(AFRICA_EXPANSION)} countries")
    print(f"File size: {len(output.encode('utf-8'))} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
